/**
 * Builds src/data/avatars.ts from whatever is sitting in public/avatars.
 *
 * A static export cannot read a directory at runtime, so the file list has to
 * be baked in at build time. This runs automatically before `npm run build`;
 * run `npm run avatars` by hand after dropping new files in, so the dev server
 * picks them up too.
 */
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { extname, join } from 'node:path';

const SOURCE_DIR = join(process.cwd(), 'public', 'avatars');
const OUTPUT = join(process.cwd(), 'src', 'data', 'avatars.ts');
const IMAGE_TYPES = new Set(['.png', '.jpg', '.jpeg', '.webp', '.avif', '.gif', '.svg']);

const files = existsSync(SOURCE_DIR)
  ? readdirSync(SOURCE_DIR)
      .filter((name) => !name.startsWith('.') && IMAGE_TYPES.has(extname(name).toLowerCase()))
      .sort()
  : [];

mkdirSync(join(process.cwd(), 'src', 'data'), { recursive: true });
writeFileSync(
  OUTPUT,
  `// Generated by scripts/generate-avatars.mjs — do not edit by hand.
// Drop images into public/avatars/ and run \`npm run avatars\`.
export const AVATARS: readonly string[] = ${JSON.stringify(files, null, 2)};
`,
);

console.log(`avatars: ${files.length} image${files.length === 1 ? '' : 's'} -> src/data/avatars.ts`);
